front: {
  url: '/',
  label: 'main page',
  sitemap_priority: 1.0,
  sitemap_changefreq: 'daily'
}
blog: {
  url: '/blog',
  label: 'blog',
  sitemap_priority: 1.0,
  sitemap_changefreq: 'daily'
}
blog_comments: {
  url: '/blog/comments',
  label: 'Комментарии',
  sitemap_changefreq: 'daily'
}
blog_article_create: {
  url: '/blog/create',
  label: '+ article',
  access_level: 4,
  sitemap_exclude: true
}
blog_article_edit: {
  url: '/blog/edit/{$id}',
  label: 'edit',
  access_level: 4,
  sitemap_exclude: true
}
blog_article_delete: {
  url: '/blog/delete/{$id}',
  label: 'delete',
  access_level: 4,
  sitemap_exclude: true
}
about: {
  url: '#about',
  label: 'about',
  hash_base: '/',
  sitemap_exclude: true
}
contacts: {
  url: '#contacts',
  label: 'contacts',
  hash_base: '/',
  sitemap_exclude: true
}
cookie_agreement: {
  url: '/agreement-cookie',
  label: 'cookie-files',
  sitemap_changefreq: 'monthly'
}
user_profile: {
  url: '/user',
  label: 'profile',
  access_level: 3,
  sitemap_exclude: true
}
user_login: {
  url: '/user/login',
  label: 'sign in',
  access_level: 1,
  sitemap_exclude: true
}
user_logout: {
  url: '/user/logout',
  label: 'sign out',
  access_level: 3,
  sitemap_exclude: true
}
feedbacks: {
  url: '/feedbacks',
  label: 'feedbacks',
  access_level: 4,
  sitemap_exclude: true
}
sitemap: {
  url: '/sitemap.xml',
  label: 'sitemap',
  sitemap_exclude: true,
  attributes: {
    target: '_blank'
  }
}
sitemap_generate: {
  url: '/sitemap/generate',
  label: 'gen. sitemap',
  access_level: 5,
  sitemap_exclude: true
}
admin_log: {
  url: '/admin/log',
  label: 'log',
  access_level: 4,
  sitemap_exclude: true
}
entity_skill_create: {
  url: '/admin/skill/create',
  label: '+ skill',
  access_level: 4,
  sitemap_exclude: true
}