front: {
  url: '/',
  label: 'main page'
}
blog: {
  url: '/blog',
  label: 'blog'
}
about: {
  url: '#about',
  label: 'about',
  hash_base: '/'
}
contacts: {
  url: '#contacts',
  label: 'contacts',
  hash_base: '/'
}
cookie_agreement: {
  url: '/agreement-cookie',
  label: 'cookie-files'
}
user_profile: {
  url: '/user',
  label: 'profile',
  access_level: 3
}
user_login: {
  url: '/user/login',
  label: 'sign in',
  access_level: 1
}
user_logout: {
  url: '/user/logout',
  label: 'sign out',
  access_level: 3
}