front: {
  url: '/',
  label: 'main page'
}
blog: {
  url: '/blog',
  label: 'blog'
}
about: {
  url: '#about',
  label: 'about'
}
contacts: {
  url: '#contacts',
  label: 'contacts'
}
cookie_agreement: {
  url: '/agreement-cookie',
  label: 'Использование cookie-файлов'
}